-- 创建AI玩家表
CREATE TABLE IF NOT EXISTS `ai_player` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT 'AI玩家名称',
  `model_type` varchar(50) NOT NULL COMMENT '模型类型',
  `model_name` varchar(255) NOT NULL COMMENT '模型名称',
  `personality` varchar(255) DEFAULT NULL COMMENT '个性',
  `strategy` varchar(255) DEFAULT NULL COMMENT '策略',
  `language` varchar(10) NOT NULL DEFAULT 'zh-CN' COMMENT '对局发言语言',
  `avatar_url` longtext DEFAULT NULL COMMENT 'AI玩家头像Data URL',
  `voice_enabled` int(11) DEFAULT '1' COMMENT '是否启用AI语音',
  `voice_engine` varchar(20) DEFAULT 'browser' COMMENT '语音引擎',
  `voice_uri` varchar(255) DEFAULT '' COMMENT '浏览器音色URI',
  `cloud_voice` varchar(60) DEFAULT 'alloy' COMMENT '云端音色',
  `voice_rate` double DEFAULT '1' COMMENT '语速',
  `voice_pitch` double DEFAULT '1' COMMENT '音调',
  `voice_volume` double DEFAULT '1' COMMENT '音量',
  `api_key` varchar(255) NOT NULL COMMENT 'API Key',
  `api_base_url` varchar(255) DEFAULT NULL COMMENT 'API Base URL',
  `temperature` int(11) DEFAULT '7' COMMENT '温度',
  `max_tokens` int(11) DEFAULT '1000' COMMENT '最大tokens',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='AI玩家表';
